services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${DB_USER:-bitrixuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-bitrixbot}
      POSTGRES_INITDB_ARGS: "--auth-local=md5 --auth-host=md5 --locale=ru_RU.UTF-8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8"
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - my_network
    restart: unless-stopped


  bot:
    container_name: app
    image: ghcr.io/tuhekocmoc/bitrix:1.0.6
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - METRICS_PORT=${METRICS_PORT:-8000}
    depends_on:
      - db
    expose:
      - "${METRICS_PORT:-8000}"
    networks:
      - my_network
    restart: unless-stopped


  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db
    networks:
      - my_network
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    pid: "host"
    privileged: true
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /run/udev:/run/udev:ro

    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($|/)'


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - my_network
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"
    networks:
      - my_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - my_network
    restart: unless-stopped

volumes:
  db-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  my_network:
    driver: bridge
