services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${DB_USER:-bitrixuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-bitrixbot}
      POSTGRES_INITDB_ARGS: "--auth-local=md5 --auth-host=md5 --locale=ru_RU.UTF-8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8"
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - my_network

  bot:
    image: ghcr.io/tuhekocmoc/bitrix:1.0.1
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable"
    depends_on:
      - db
    networks:
      - my_network

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    networks:
      - my_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres-exporter
      - node-exporter
      - cadvisor
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - my_network

volumes:
  db-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  my_network:
    driver: bridge
